### ISSUE TITLE
Choices should be surrounded with brackets

### ISSUE THREAD

**Issue by Hugman76** [Dhranios/Luigi-s-Mansion#16]
Example:
![image](https://user-images.githubusercontent.com/36963654/122597064-2245a600-d06b-11eb-9501-91ef8eb90705.png)

**Comment by Dhranios** [comment]
not square brackets, using those for hover events; I think the text being green is fine, but then explaining it at the start of the map.

**Comment by Dhranios** [comment]
Did not add brackets, but instead show explanation of the formatting when you enter the world.
