### ISSUE TITLE
Hidden Mansion mirror room

### ISSUE THREAD

**Issue by Chazm63** [Dhranios/Luigi-s-Mansion#41]
When I go into the mirror room in the hidden mansion the door doesn't lock behind me so the mirror ghosts don't spawn. This is the second time this has happened so I know its not a one time thing.

**Comment by Dhranios** [comment]
Found the issue, and I know how to fix it; it's a remnant of an older system to prevent blockades spawning inside you.

I'll push a change for most rooms to prevent this ever being an issue again.

I wonder how I missed this in my test run...

**Comment by Chazm63** [comment]
can I fix it without restarting?

**Comment by Dhranios** [comment]
It's fixed in the commit; the room should start immediately when you're inside it.
