### ISSUE TITLE
After loading in new mansion exterior ghosts don't enter dying state properly; caused by occasional remnant entity

### ISSUE THREAD

**Issue by Chazm63** [Dhranios/Luigi-s-Mansion#42]
on the hidden mansion the ghosts are now going down to zero but not getting sucked up.

**Comment by Dhranios** [comment]
I'm puzzled by this, I didn't tough ghost harming in the commits to the hotfixes.
Are you perhaps in a developmental build (commit pushed here, but no release)?

**Comment by Chazm63** [comment]
I downloaded the update you did last. but I had to restart the last time cause I don't know how to overwrite the old save

**Comment by Dhranios** [comment]
So version 1.3; and it worked fine in 1.2 per #41.

**Comment by Chazm63** [comment]
yeah

**Comment by Chazm63** [comment]
I always seem to find new issues when I get to the hidden mansion

**Comment by Dhranios** [comment]
Could you send me a copy of your world? I can't seem to trigger it in any of the releases when loading in the hidden mansion.

**Comment by Chazm63** [comment]
How do I send you my world?

**Comment by Dhranios** [comment]
Upload it somewhere (eg mediafire, dropbox or google drive), and send me the link

**Comment by Dhranios** [comment]
> I downloaded the update you did last. but I had to restart the last time cause I don't know how to overwrite the old save

BTW, how to do this is explained in the installing and notes.txt

**Comment by Chazm63** [comment]
yeah sorry it's taking a long time I'm uploading it to google drive

**Comment by Chazm63** [comment]
It’s fixed it’s self I just reloaded the hidden mansion

**Comment by Dhranios** [comment]
Hmmm, odd...
