### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Fireworkstars46** [Dhranios/Luigi-s-Mansion#46]
What's the what way to Kill the ghosts the fastest with the most kits etc with the poltergust?

**Comment by Dhranios** [comment]
It's explained in the training room:
1. flash the ghost with your flashlight
2. Attack the ghost with the poltergust
3. (once they start fleeing) move away from the ghost to harm it
4. (this is missing in the training room's current version but will be added/mentioned in it in the next version; that said, it does already work) constantly switch between sneaking and standing to deal damage at an accelerated rate

**Comment by Fireworkstars46** [comment]
I know to move away to harm it, but if I'm in a corner, what would I do then?

**Comment by Dhranios** [comment]
That's the trick, think ahead of time to avoid corners, if needed, move to the ghost and get out of the corner, and move away again as quickly as possible
In the next update, if you don't move away from it for 1/4th of a second, it counts as a player error, 10 errors and the ghost escapes.

**Comment by Fireworkstars46** [comment]
Also for the white grabbing ghost, how exactly do I get them off of me?

**Comment by Dhranios** [comment]
Creating as much distance in  tick as possible (try jumping). This alao is improved in rhe next version. 😁

**Comment by Fireworkstars46** [comment]
Is it possible to quit without saving? Like reload my save?

**Comment by Dhranios** [comment]
You can talk to E. Gadd to load old save data. :)

**Comment by Fireworkstars46** [comment]
As for the boos, is there a way to check how many I got so far?

**Comment by Dhranios** [comment]
No, sorry, even in the development versions it is not visible yet. I'm not sure where/how to show it to the players.

**Comment by Fireworkstars46** [comment]
For the map in the game boy horror, is it possible to zoom in or no?

**Comment by Dhranios** [comment]
No; next version will zoom in/out on map when collecting a key, but no option to zoom in still

**Comment by Fireworkstars46** [comment]
Idk why but I only got 2 out of 3 skeleton ghosts before the graveyard boss.

**Comment by Dhranios** [comment]
It may be you're standing in the exact spot the ghost wants to appear, or that the you didn't get close enough and look away from the ghost.
Or do you mean you only caught 2 and bogmire was ready?

**Comment by Fireworkstars46** [comment]
Like 2 appeared and got them but after I got them the 3rd one never appeared. I tried hitting/vacuuming the gravestone again and the last one didn't come out anymore. In the end I chose to kill myself to reset it and after that they all appeared.

**Comment by Dhranios** [comment]
If you run into this issue again, make a new github issue and provide me a download of your world so I can investigate it.

**Comment by Fireworkstars46** [comment]
Also the boos kinda hack or a little buggy. Idk if it's me or not but when I suck them, I damage them but sometimes they start attacking me when I damage them and I die so fast and can't escape.

**Comment by Dhranios** [comment]
Known issue that has been resolved for v1.4

**Comment by Fireworkstars46** [comment]
So someone already catched that bug?

**Comment by Dhranios** [comment]
I had been aware of it for a while, there were 3 things wrong:
1. Boos can trigger attack while fleeing
2. Boos get pulled with you by the poltergust when you collide with them
3. Small invulnerability timer

Fixed the first (but they can still chose to go into another direction (different target room to flee to)) and added knockback, during which you cannot use the poltergust, and get pushed back, fixing the second and third.

**Comment by Fireworkstars46** [comment]
As for the twins room, is there a tip for guessing their hiding spot?

**Comment by Dhranios** [comment]
See Neville's Child-Care Diary; no visible shaking or sound, so uses particles.

**Comment by Fireworkstars46** [comment]
Do I have to look away or it doesn't matter?

**Comment by Dhranios** [comment]
No, it doesn't matter, initial appearing (mobiel) is just spinning it for long enough, hide and seek is opening chest

**Comment by Fireworkstars46** [comment]
Well nothings happening (particles etc) xD

**Comment by Dhranios** [comment]
It's a circular pattern on the floor at the chest, same kind as the poltergust, so you need to check closely. If you checked them all and can't find 2 of them giving particles (assuming you didn't open any chest yet; if you did, and it was wrong, leave the room), please provide me a download of the world you use (and say which mansion).

**Comment by Fireworkstars46** [comment]
I didn't open any yet

**Comment by Dhranios** [comment]
Could you record a video of you using the poltergust on every chest (around a second per chest so the particles have time to be properly visible), and with particles turned on?

**Comment by Fireworkstars46** [comment]
Well I found out one thing. If I use the poltergust on 1 chest, it's blank. If I try a different one, I see a ring of particles around it. Is that what you mean?

**Comment by Dhranios** [comment]
Yes, it is.

**Comment by Fireworkstars46** [comment]
Well the map is broken now. I skipped the e-gad talk after the boos go round on the balcony and then I left to e-gad's underground lab and when I reloaded the save, I tried to enter the mansion and now I can't enter anymore. The door is stick like it's locked

**Comment by Dhranios** [comment]
Go to the mansion again, via E. Gadd, see if that corrects the map.
For bug tracking reasons, could you tell me what the last moment you saved was?

**Comment by Fireworkstars46** [comment]
Before the boos fight. I tried the mansion option and the old save option as well as relogging the map

**Comment by Dhranios** [comment]
Please send me data/scoreboard.dat and data/command_storage_luigis_mansion.dat

**Comment by Fireworkstars46** [comment]
Ok here's the files

 https://www.mediafire.com/folder/09oy5euxe3s5t/Files+for+map+dev

**Comment by Dhranios** [comment]
Ok, I found the issue, seems you got into the lab while the blackout was active, the blackout prevents opening the boo woods-foyer door.
I'll fix it for the next version (it's not something you'll have happen often), for now, you can fix your data by running **/tag @s remove blackout**

**Comment by Fireworkstars46** [comment]
As for the toads, is there any on the 2 floor and 3rd?

**Comment by Dhranios** [comment]
Toads match the locations in the original games, foyer, balcony (2F), washroom (1F), courtyard, telephone room (first/second phone, blackout only, no saving)

**Comment by Fireworkstars46** [comment]
As for the blackout, is there 2 or 3 lightning strikes?

**Comment by Dhranios** [comment]
One of each side of the mansion (left and right), and finally one striking the rooftop.
Due to how lightning works in minecraft, they only stay a random time between 0 and 1 seconds.

**Comment by Fireworkstars46** [comment]
As for the golden mouse in the sealed room, how exactly do I make it appear? Like the best technique

**Comment by Dhranios** [comment]
It's a 1 in 5 chance when the room loads, sucks, but that's how it works in the game.

**Comment by Fireworkstars46** [comment]
So I have to leave the room and enter it over and over till it works?

**Comment by Dhranios** [comment]
Yeah...

**Comment by Fireworkstars46** [comment]
Ok the mouse finally appeared but I don't see it anywhere 🤔

**Comment by Dhranios** [comment]
It starts next to the fireplace, and goes to the mirror; when it reaches the mirror, it vanishes again. It will try spawning again on new room load

**Comment by Fireworkstars46** [comment]
What exactly do you mean by new room?

**Comment by Dhranios** [comment]
new room *load*, as in the room needs to be reset again, and loading in the room again will try to spawn it again until you catch it, or light up the room

**Comment by Fireworkstars46** [comment]
Like the same room?

**Comment by Fireworkstars46** [comment]
I'm confused what you mean xD

**Comment by Dhranios** [comment]
The same as before: The mouse will (sometimes) reappear on room re-entry if you didn't catch it

**Comment by Fireworkstars46** [comment]
Well the mouse appears and as soon as I get close to it to get it, it's gone (like it's too fast or a bug)

**Comment by Dhranios** [comment]
I intent to go over all ghost health one more time somewhere this update, so they should become easier to catch.

**Comment by Dhranios** [comment]
Closing this now. I just enabled the discussions tab, so feel free to use that in the future.

**Comment by Fireworkstars46** [comment]
Is the 1.5 the new improved version?

**Comment by Dhranios** [comment]
1.4 was the improved version, 1.5 fixed some bugs in it

**Comment by Fireworkstars46** [comment]
Is 1.18.1 or 18.2 the version I should use?

**Comment by Dhranios** [comment]
1.18.2

**Comment by Fireworkstars46** [comment]
All this time I was using 18.1

**Comment by Fireworkstars46** [comment]
For the table cloth in the breaker room, what's the best way to suck it up?

**Comment by Dhranios** [comment]
There's no "best way", you just have to vacuum 2 seconds to suck up cloth, and you're limited in your distance from said cloth.
Cloth only prevents searching furniture if there's a boo insaid furniture, not any other ghost.

**Comment by Fireworkstars46** [comment]
Cause I wait for like 30 secs sucking it in multiple angles etc and nothings happening

**Comment by Dhranios** [comment]
2 seconds should be enough, and you should get forced to look at it once you grab it.
Did you get the pop sound (poltergust 3000 swallows subtitle)? Which mansion did this happen in, normal, hidden or 3DS hidden?

**Comment by Fireworkstars46** [comment]
Normal and I didn't hear the pop

**Comment by Fireworkstars46** [comment]
Here's a video recording of it  

https://streamable.com/jnzsls

**Comment by Dhranios** [comment]
Hmm, seems like it does grab, just never fully vacuum.
I'll take a look at what's different here.

**Comment by Dhranios** [comment]
Found the cause, and created #56 for it.
For further discussion, please use the discussion created for version 1.4/1.5, rather than this issue.

**Comment by Fireworkstars46** [comment]
Let me know when the bugs are fixed

**Comment by Fireworkstars46** [comment]
What bug fixes is in v1.6?

**Comment by Dhranios** [comment]
I can't say for certain which were development only, and which were in the release, but you can check the last 10 commit descriptions on the master branch to get a decent idea what got fixed. As well as the closed reports which were set to v1.6.

**Comment by Dhranios** [comment]
You need to install them if you want to use them; how to is explained in the download.

**Comment by Fireworkstars46** [comment]
What exactly does each addon do?

**Comment by Dhranios** [comment]
Oh wow, I didn't realize this wasn't explained anywhere, I'll make sure to correct that.

3DS Remake: Makes the map match the 3DS version of Luigi's Mansion, adding the new gallery, changing the hidden mansion, and a couple AI and dialog changes.

Extensive Training: Adds 2 more training room programs to help hone your skills; also adds tasks and an amiibo.

**Comment by Fireworkstars46** [comment]
Map meaning the map I enter to scroll and check the rooms etc if they're open or locked?

**Comment by Dhranios** [comment]
The world.

**Comment by Fireworkstars46** [comment]
Is there a screenshot you can share comparing the 2 (with 3DS and without it)?
